[formatting]
reorder_arrays = true
reorder_keys = false
align_comments = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.denpendencies"]

[rule.formatting]
reorder_keys = true
