#!/usr/bin/env bash
set -euo pipefail

ARGS="--manifest-path $MANIFEST"

if [[ ${1:-} == "release" ]]
then
	PROFILE="release"
	ARGS="--release $ARGS"
else
	PROFILE="debug"
fi

echo "🐍⚡ Compiling Server..."
cargo build $ARGS -p typhon-server
echo ""

echo "🐍⚡ Compiling App..."
cargo build $ARGS -p typhon-app --target wasm32-unknown-unknown --features hydrate
echo ""

echo "🐍⚡ Packaging..."
SITE_ROOT=$ROOT/site/$PROFILE
INPUT=$WORKSPACE/target/wasm32-unknown-unknown/$PROFILE
OUTPUT=$SITE_ROOT/pkg
if [[ ! -f $OUTPUT/typhon_bg.wasm ]] || [[ $(date -r $OUTPUT/typhon_bg.wasm +%s) < $(date -r $INPUT/typhon_app.wasm +%s) ]]
then
	rm -rf $OUTPUT
	cargo run $ARGS -p typhon-pack -- $OUTPUT $INPUT/typhon_app.wasm
	du -ch $OUTPUT/*
fi
echo ""
echo "🐍⚡ Done!"
echo ""
